#!/usr/bin/sh
if [ $1 = "clear" ]; then
   rm -rf output
fi
DATA_DIR="${HOME}"/pet/data/atomic
OUTPUT_DIR="${HOME}"/pet/output
TASK=atomic
MODEL_NAME_OR_PATH="roberta-base"
MODEL_TYPE=roberta
python3 cli.py \
--method pet \
--pattern_ids 0 \
--data_dir $DATA_DIR \
--model_type $MODEL_TYPE \
--model_name_or_path $MODEL_NAME_OR_PATH \
--task_name $TASK \
--output_dir $OUTPUT_DIR \
--do_train \
--do_eval \
--pet_per_gpu_eval_batch_size=1 \
--train_examples=1000 \
--pet_max_seq_length=40 \
--sc_max_seq_length=250

