#!/usr/bin/sh
DATA_DIR="${HOME}"/pet/data/atomic
TASK=atomic
MODEL_NAME_OR_PATH="SpanBERT/spanbert-base-cased"
dir="$(basename $MODEL_NAME_OR_PATH)"
dir="span_bert_21k_9k_nn"
OUTPUT_DIR="${HOME}"/pet/output_"${dir}"
if [ $1 = "clear" ]; then
   rm -rf "${OUTPUT_DIR}"
fi
MODEL_TYPE=bert
python3 cli.py \
--method pet \
--pattern_ids 0 \
--data_dir $DATA_DIR \
--model_type $MODEL_TYPE \
--model_name_or_path $MODEL_NAME_OR_PATH \
--task_name $TASK \
--output_dir $OUTPUT_DIR \
--do_eval \
--overwrite_output_dir \
--pet_per_gpu_eval_batch_size=1 \
--pet_per_gpu_train_batch_size=1 \
--train_examples=45000 \
--unlabeled_examples=1000  \
--split_examples_evenly \
--pet_max_seq_length=60 \
--sc_max_seq_length=150 \
--pet_num_train_epochs=1 \
--sc_num_train_epochs=1 \
--do_train \
