#!/usr/bin/sh
pet_dir="/drive2/pouramini/pet"
DATA_DIR="${pet_dir}/data/atomic"
TASK=atomic_xeffect
MODEL_NAME_OR_PATH="roberta-base"
dir="$(basename $MODEL_NAME_OR_PATH)"
dir="roberta_10k_1k_${TASK}"
OUTPUT_DIR="${pet_dir}"/output_"${dir}"
if [ $1 = "clear" ]; then
   rm -rf "${OUTPUT_DIR}"
fi
MODEL_TYPE=roberta
python3 cli.py \
--method pet \
--pattern_ids 0 \
--data_dir $DATA_DIR \
--model_type $MODEL_TYPE \
--model_name_or_path $MODEL_NAME_OR_PATH \
--task_name $TASK \
--output_dir $OUTPUT_DIR \
--overwrite_output_dir \
--pet_per_gpu_eval_batch_size=32 \
--pet_per_gpu_train_batch_size=32 \
--unlabeled_examples=1000  \
--pet_max_seq_length=60 \
--sc_max_seq_length=150 \
--pet_num_train_epochs=1 \
--sc_num_train_epochs=1 \
--do_eval \
--do_train \
#--train_examples=10000 \
#--split_examples_evenly \
